version: 2

builds:
  - main: .
    binary: my-get
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats: [ 'binary' ]
    name_template: "{{ .Binary }}_{{ .Arch }}"